services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    App\Baz\Application\:
        resource: '../../../Application/*'

    App\Baz\Infrastructure\:
        resource: '../../../Infrastructure/*'