foo_api:
    resource: ../src/Foo/Api/
    type: annotation
    prefix: api

bar_api:
    resource: ../src/Bar/Api/
    type: annotation
    prefix: api

kernel:
    resource: ../src/Kernel.php
    type: annotation
