product_api:
    resource: ../src/Product/Api/
    type: annotation
    prefix: api

cart_api:
    resource: ../src/Cart/Api/
    type: annotation
    prefix: api

kernel:
    resource: ../src/Kernel.php
    type: annotation
